print(type(8))
print(type(5.3))
print(type('A'))
print(type(True))
print(type(False))

print(float(3))
print(int(5.6))
print(str(9))
print(str('455'))
print(int(True))
print(int(False))
print(bool(0))
print(bool(1))